extreme:
  forecast: "fdb:ens"
  climatology: "fdb:clim"
ensemble:
  forecast: "mars:ens"
ensemble_anomaly:
  forecast: "fdb:ens"
  climatology: "fdb:clim"
clustereps:
  mask: none
  spread: none 
  spread-compute: ["fdb:spread_z500", "mars:spread_z500"]
  ensemble: "fdb:ens_z500"
  deterministic: "fdb:determ_z500"
  clim-dir: "REQUIRED"
  pca: none
  centroids: none 
  representative: none 
  cen-anomalies: none 
  rep-anomalies: none 
  indexes: none 
  ncomp-file: none 
  output-root: "CWD"