global:
  members:
    end: 5
    start: 1
common:
  interpolate:
    grid: O1280
    intgrid: none
    legendre-loader: shmem
    matrix-loader: file-io
  sources:
    fdb:
      ens: {}
    mars:
      ens: {}
params:  
  207:
    param:
      id: [165, 166]
      operation: norm
    grib_set:
      indicatorOfParameter: 207
      gribTablesVersionNo: 128
  228249:
    param: 
      id: [228246, 228247]
      operation: norm
    grib_set:
      indicatorOfParameter: 249
      gribTablesVersionNo: 228
  200228:
    param:
      id: 228
    grib_set:
      stepType: diff
      timeRangeIndicator: 5
    windows:
      operation: diff
      include_start_step: True
  260048:
    param:
      id: 260048
      scale: 3600
  260050:
    param:
      id: [228219, 228221]
      operation: sum
      scale: 3600
    grib_set:
      paramId: 228221
  260033:
    param:
      id: [228220, 228218]
      operation: sum
      scale: 3600
    grib_set:
      edition: 2
      shortName: tprate
  260053:
    param:
      id: [228220, 228221]
      operation: sum
      scale: 3600
    grib_set:
      edition: 2
      shortName: tprate
  # 228:
  #   param:
  #     id: 228
  #   grib_set:
  #     paramId: 200228
  #     stepType: diff
  #   windows:
  #     operation: diff
  #     include_start_step: True
  10:
    param:
      id: [138, 155]
      operation: wind_speed
    interpolate:
      vod2uv: "1"
    grib_set:
      gribTablesVersionNo: 128
      indicatorOfParameter: 10
products:
  em/es: 
    global:
      out_keys:
        perturbationNumber: 0
        bitsPerValue: 16
    common:
      sources:
        fdb:
          ens:
            - type: pf
            - type: cf
        mars:
          ens:
            - type: pf
            - type: cf
      ensemble:
        operation:
          em: mean
          es: std
  ep:
    global:
      out_keys:
        type: ep
        localDefinitionNumber: 5
        bitsPerValue: 8
    common:
      sources:
        fdb:
          ens:
            type: pf
        mars:
          ens:
            type: pf
    params:
      131060: 
        param: 
          id: 228
        windows:
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 0.001
          local_scale_factor: 3
        grib_set:
          timeRangeIndicator: 5
          stepType: diff 
      131061:
        param: 
          id: 228
        windows:
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 0.005
          local_scale_factor: 3
        grib_set:
          timeRangeIndicator: 5
          stepType: diff 
      131062: 
        param: 
          id: 228
        windows:
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 0.01
          local_scale_factor: 3
        grib_set:
          timeRangeIndicator: 5
          stepType: diff 
      131063:
        param: 
          id: 228
        windows:
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 0.02
          local_scale_factor: 3
        grib_set:
          timeRangeIndicator: 5
          stepType: diff 
      131064:
        param: 
          id: 228
        windows:
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: "<"
          value: 0.0001
          local_scale_factor: 4
        grib_set:
          timeRangeIndicator: 5
          stepType: diff 
      131065:
        param: 
          id: 228
        windows:
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: "<"
          value: 0.001
          local_scale_factor: 4
        grib_set:
          timeRangeIndicator: 5
          stepType: diff 
      131066:
        param: 
          id: 228
        windows:
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 0.003
          local_scale_factor: 4
        grib_set:
          timeRangeIndicator: 5
          stepType: diff 
      131067:
        param: 
          id: 228
        windows:
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 0.005
          local_scale_factor: 4
        grib_set:
          timeRangeIndicator: 5
          stepType: diff 
      131098:
        param: 
          id: 228
        windows: 
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 0.025
          stepType: accum
        grib_set:
          stepRange: 0-0
          edition: 2
          scaleFactorOfLowerLimit: 0
          probabilityType: 3
          typeOfGeneratingProcess: 5
          indicatorOfUnitForTimeIncrement: 1
          timeIncrement: 12
          packingType: grid_ccsds
          scaleFactorOfUpperLimit: MISSING
          scaledValueOfUpperLimit: MISSING
      131099:
        param: 
          id: 228
        windows: 
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 0.05
          stepType: accum
        grib_set: 
          stepRange: 0-0
          edition: 2
          scaleFactorOfLowerLimit: 0
          probabilityType: 3
          typeOfGeneratingProcess: 5
          indicatorOfUnitForTimeIncrement: 1
          timeIncrement: 12
          packingType: grid_ccsds
          scaleFactorOfUpperLimit: MISSING
          scaledValueOfUpperLimit: MISSING  
      131085:
        param: 
          id: 228
        windows: 
          operation: 'diff'
          include_start_step: True
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 0.1
          stepType: accum
        grib_set: 
          stepRange: 0-0
          edition: 2
          scaleFactorOfLowerLimit: 0
          probabilityType: 3
          typeOfGeneratingProcess: 5
          indicatorOfUnitForTimeIncrement: 1
          timeIncrement: 12
          packingType: grid_ccsds
          scaleFactorOfUpperLimit: MISSING
          scaledValueOfUpperLimit: MISSING  
      131068:
        steps: 
          - [12, 360, 12]
        param: 
          id: [165, 166]
          operation: 'norm'
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 10
      131069:
        steps: 
          - [12, 360, 12]
        param: 
          id: [165, 166]
          operation: 'norm'
        ensemble:
          operation: threshold_prob
          comparison: ">="
          value: 15
      131073:
        steps: 
          - [12, 240, 12]
          - [123, 144, 3]
          - [150, 240, 6]
          - [228, 360, 12]
          - [246, 360, 6]
        param: 
          id: 122
        ensemble:
          operation: threshold_prob
          comparison: "<="
          value: 273.15
          local_scale_factor: 2
        windows: 
          operation: minimum
      131070:
        param:
          id: 123
        steps: 
          - [6, 240, 6]
        ensemble:
          operation: threshold_prob
          comparison: '>='
          value: 15
      131071:
        param:
          id: 123
        steps: 
          - [6, 240, 6]
        ensemble:
          operation: threshold_prob
          comparison: '>='
          value: 20
      131072:
        param:
          id: 123
        steps: 
          - [6, 240, 6]
        ensemble:
          operation: threshold_prob
          comparison: '>='
          value: 25
      131100:
        param:
          id: 123
        steps: 
          - [6, 240, 6]
        ensemble:
          operation: threshold_prob
          comparison: '>='
          value: 10
        grib_set:
          edition: 2
          indicatorOfUnitForTimeIncrement: 1
          packingType: grid_ccsds
          productDefinitionTemplateNumber: 9
          scaleFactorOfUpperLimit: MISSING
          scaledValueOfUpperLimit: MISSING
          timeIncrement: 12
          typeOfGeneratingProcess: 5
          typeOfTimeIncrement: 2
      131074:
        param:
          id: 140229
        steps:
          - [12, 240, 12]
          - [123, 144, 3]
          - [150, 240, 6]
          - [228, 360, 12]
          - [246, 360, 6]
        grib_set:
          timeRangeIndicator: 0
        ensemble:
          operation: threshold_prob
          comparison: '>='
          value: 2
      131075:
        param:
          id: 140229
        steps:
          - [12, 240, 12]
          - [123, 144, 3]
          - [150, 240, 6]
          - [228, 360, 12]
          - [246, 360, 6]
        ensemble:
          operation: threshold_prob
          comparison: '>='
          value: 4
      131076:
        param:
          id: 140229
        steps:
          - [12, 240, 12]
          - [123, 144, 3]
          - [150, 240, 6]
          - [228, 360, 12]
          - [246, 360, 6]
        ensemble:
          operation: threshold_prob
          comparison: '>='
          value: 6
      131077:
        param:
          id: 140229
        steps:
          - [12, 240, 12]
          - [123, 144, 3]
          - [150, 240, 6]
          - [228, 360, 12]
          - [246, 360, 6]
        ensemble:
          operation: threshold_prob
          comparison: '>='
          value: 8
      131022: # t850
        steps:
          - [0, 360, 12]
        param: 
          id: 130
        sources:
          fdb:
            ens:
              type: cf/pf
            clim:
              stream: efhs
              type: em/es
          mars:
            ens:
              type: cf/pf
            clim:
              stream: efhs
              type: em/es
        ensemble:
          operation: threshold_prob
          comparison: <
          value: -8
        grib_set:
          bitsPerValue: 24
        windows:
          operation: mean 
      133093: # t850
        steps:
          - [0, 360, 12]
        param: 
          id: 130
        sources:
          fdb:
            ens:
              type: cf/pf
            clim:
              stream: efhs
              type: em/es
          mars:
            ens:
              type: cf/pf
            clim:
              stream: efhs
              type: em/es
        ensemble:
          operation: threshold_prob
          comparison: ">"
          value: -1
        grib_set:
          localDefinitionNumber: 30
          bitsPerValue: 24
          edition: 2
          typeOfGeneratingProcess: 5
          paramId: 0
          timeIncrement: 12
          indicatorOfUnitForTimeIncrement: 1
          typeOfStatisticalProcessing: 10
          packingType: grid_ccsds
          scaleFactorOfUpperLimit: MISSING
          scaledValueOfUpperLimit: MISSING
        windows:
          operation: mean
          std_anomaly: True
  pb:
    global:
      out_keys:
        type: "pb"
    common:
      sources:
        fdb:
          ens:
            - type: pf
            - type: cf
        mars:
          ens:
            - type: pf
            - type: cf
      ensemble: 
        operation: quantiles
  efi/efic/sot:
    global:
      out_keys:
        bitsPerValue: 12
    common:
      steps: 
        - [0, 360, 6]
      sources:
        fdb:
          ens:
            - type: pf
            - type: cf
          clim:
            stream: efhs
            type: cd
            quantile: 100
        mars:
          ens:
            - type: pf
            - type: cf
          clim:
            stream: efhs
            type: cd
            quantile: 100
      ensemble:
        operation: 
          efi: efi
          sot: sot
          efic: efi
        eps: 1e-4
    params:
      132167:
        param:
          id: 167
        sources:
          fdb:
            clim: 
              param: 228004
          mars:
            clim: 
              param: 228004
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 167
          localDefinitionNumber: 19
          timeRangeIndicator: 3
        windows:
          operation: mean
      132202:
        param:
          id: 122
        sources:
          fdb:
            clim:
              param: 202
          mars:
            clim:
              param: 202
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 202
          localDefinitionNumber: 19
          timeRangeIndicator: 2
        windows:
          operation: minimum
      132201:
        param:
          id: 121
        sources:
          fdb:
            clim:
              param: 201
          mars:
            clim:
              param: 201
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 201
          localDefinitionNumber: 19
          timeRangeIndicator: 2
        windows:
          operation: maximum
      132165:
        param:
          id: 207
        sources:
          fdb:
            clim: 
              param: 228005
          mars:
            clim: 
              param: 228005
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 165
          localDefinitionNumber: 19
          timeRangeIndicator: 3
        windows:
          operation: maximum
      132049:
        param:
          id: 123
        sources: 
          fdb:
            clim:
              param: 49 
          mars:
            clim:
              param: 49 
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 49
          localDefinitionNumber: 19
          timeRangeIndicator: 2
        windows:
          operation: maximum
      132216:
        steps: 
        - [0, 360, 6]
        param:
          id: 229
        sources:
          clim:
            fdb:
              param: 140200
              stream: wehs
            mars:
              param: 140200
              stream: wehs
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 216
          localDefinitionNumber: 19
          timeRangeIndicator: 2
        windows:
          operation: maximum
      132228:
        steps:
        - [0, 360, 6]
        param:
          id: 228
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 228
          localDefinitionNumber: 19
          timeRangeIndicator: 5
        windows:
          operation: diff
          include_start_step: True
      132144:
        steps:
        - [0, 360, 6]
        param:
          id: 144
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 144
          localDefinitionNumber: 19
          timeRangeIndicator: 5
        windows:
          operation: diff    
          include_start_step: True 
      132045:
        steps:
        - [0, 360, 6]
        param:
          id: [162071, 162072]
          operation: norm
        sources:
          fdb:
            clim:
              param: 162045
          mars:
            clim:
              param: 162045
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 45
          localDefinitionNumber: 19
          timeRangeIndicator: 3
        window: 
          operation: mean
      132059:
        steps:
        - [0, 360, 6]
        param:
          id: [228035, 228035]
          operation: filter
          comparison: <=
          threshold: 10
        sources:
          fdb:
            clim: 
              param: 59
          mars:
            clim: 
              param: 59
        grib_set:
          edition: 1
          gribTablesVersionNo: 132
          indicatorOfParameter: 59
          indicatorOfTypeOfLevel: 1
          localDefinitionNumber: 19
          timeRangeIndicator: 2
          typeOfStatisticalProcessing: 1  
        windows:
          operation: maximum
      132044:
        steps:
        - [0, 360, 6]
        param:
          id: [228036, 228035]
          operation: filter
          comparison: <=
          threshold: 10
        sources:
          fdb:
            clim:
              param: 228044
          mars:
            clim:
              param: 228044
        grib_set:
          param: 228035
          typeOfStatisticalProcessing: 1
          edition: 1
          indicatorOfTypeOfLevel: 1
          timeRangeIndicator: 2
          indicatorOfParameter: 44
          gribTablesVersionNo: 132
          localDefinitionNumber: 19
        windows:
          operation: maximum